### ISSUE TITLE
Don't see the recipe for water condenser within minecraft (Minecraft: 1.21.1 Neoforge: 21.1.64 Water Condenser: 1.5.0)

### ISSUE THREAD

**Issue by DatrixTheHybridShadowWolf** [oierbravo/watercondenser#11]
Hi there,

I have this hunch that this has something to do with sinytra connector/forge-ified fabric API as this has happened before from another mod I played around with such as Large Fluid Tanks. This is Kotori316's words to me as to what is happening: "It seems the fabric API conflicts with recipe condition and he adds conditions for all platforms into just one file, and the fabric API might load the condition for fabric, but fails as it runs on Forge." 

I know you have this mod working for Forge and Neo Forge so I can only guess that the same thing applies to both mod loaders as it will work for Forge but when used with Neo Forge it won't load the conditions. I'm more than likely incorrect, but that is just my inference on the matter.

Minecraft: 1.21.1
Neo Forge: 21.1.64
Water Condeser: 1.5.0
Forge-ified Fabric: 0.104.0
Sinytra Connector: 2.0.0-beta2

Picture of issue...I'm hoping this is the way to create the condenser since I took a look at the recipe on your github code page: 
![2024-09-30_04 29 07](https://github.com/user-attachments/assets/3bf75dc8-8787-4335-8b27-e2d76612d4f2)

Log: 
[latest.log](https://github.com/user-attachments/files/17186562/latest.log)

**Comment by oierbravo** [comment]
Hi!
There was an error in the recipe included.
Thanks for the report!!

**Comment by DatrixTheHybridShadowWolf** [comment]
You're welcome and thanks for the response.
