### ISSUE TITLE
Water condenser does not drop itself when broken.

### ISSUE THREAD

**Issue by cuberyl-catastrophe** [oierbravo/watercondenser#7]
Even when broken with a pickaxe, the water condenser doesn't drop itself.

Tested in the Nomifactory Modern modpack. There is no reason for any other mods to be breaking this.

**Comment by Leclowndu93150** [comment]
may i add that it does not have a tool assigned to it

**Comment by oierbravo** [comment]
Hi!
Thanks for the report.
Adding `axe` and `pickaxe` as tools.

**Comment by TheLonelySoul12345** [comment]
It doesn't drop itself again
Mod version: 1.6.0, Minecraft version: 1.21.1, NeoForge Version: 21.1.233
I looked in the files and they do have the axe and pickaxe files there, but they don't seem to actually apply to the item for some reason, as the Jade window doesn't show them as the proper tools
couldn't it be possible that it drops itself even without a tool like most wood items, and axes make it faster?
