### ISSUE TITLE
Water condenser causes chunks not to load for clients on servers

### ISSUE THREAD

**Issue by cuberyl-catastrophe** [oierbravo/watercondenser#8]
Chunks with a water condenser in them will fail to get loaded on servers.

To reproduce:
Place a water condenser in a chunk on a server
Leave the area
Return to the area

The chunk will not load for clients anymore.

Happens in Nomifactory Modern. I don't have a server to test this mod alone.

**Comment by DoughnutDev** [comment]
This happens on a server also with the base Nomifactory Modern with no added mods. I do have citresewn disabled and effortless building downgraded to version 3.7 so it runs on a server.

**Comment by oierbravo** [comment]
Thanks for the report!
Working on it!
